### PR TITLE
Changed Whitelist terms to Allow List  :D 

### PR DESCRIPTION
**Pull request by WillStrohl**
This update is only cosmetic and doesn't update the back-end yet.  

image

### CODE REVIEW

**Comment by mitchelsellers** [comment]
I am curious for community input on this one.  Whitelist is a common, approved, technical term for what is being done here.  

I'm not against this one necessarily but curious to others opinions

**Comment by WillStrohl** [comment]
> I am curious for community input on this one. Whitelist is a common, approved, technical term for what is being done here.
> 
> I'm not against this one necessarily but curious to others opinions

This is along the same lines as the rename by GitHub from `master` to `main` for the default branch.

**Comment by bdukes** [comment]
It's included on, e.g., https://www.acm.org/diversity-inclusion/words-matter as well as https://standards.ieee.org/about/sasb/resolutions.html

>IEEE standards (including recommended practices and guides) shall be written in such a way as to unambiguously communicate the technical necessities, preferences, and options of the standard to best enable market adoption, conformity assessment, interoperability, and other technical aspirations of the developing standards committee. IEEE standards should be written in such a way as to avoid non-inclusive and insensitive terminology (see IEEE Policy 9.27) and other deprecated terminology (see clause 10 of the IEEE SA Style Manual) except when required by safety, legal, regulatory, and other similar considerations. Terms such as master/slave, blacklist, and whitelist should be avoided.

**Comment by mitchelsellers** [comment]
Well approved then

**Review by mitchelsellers — APPROVED** [review]

**Pull request merged**
